wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.2
    start_time: 1631424971
    t:
      1:
      - 2
      - 3
      - 5
      2:
      - 2
      - 3
      - 5
      3:
      - 2
      - 3
      - 8
      4: 3.9.2
      5: 0.12.1
      8:
      - 1
      - 3
      - 5
architecture:
  desc: null
  value: CNN
batch_size:
  desc: null
  value: 32
dataset:
  desc: null
  value: MNIST
epochs:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.001
loss_function:
  desc: null
  value: sparse_categorical_crossentropy
